### ISSUE TITLE
Biomes O plenty

### ISSUE THREAD

**Issue by dazadazu** [Harleyoc1/DynamicTreesVampirism#1]
The biome trees in "Ominous Woods" from Biomes O Plenty have all been replaced by the spruce dynamic tree from Vampirisim.

**Comment by dazadazu** [comment]
Actually a lot of biomes have been affected, so weird. Fen biome on the left and ominous woods biome on the right. Both have vampirisim dynamic spruce tree... You can google Fen biome to see what the trees should really look like.

![Mabu](https://user-images.githubusercontent.com/73519218/98797946-22d5da00-23c2-11eb-81c4-4930a668879b.jpg)

https://gyazo.com/3770db12e70b72e4f6baafdb25fd62ec

**Comment by Harleyoc1** [comment]
I’ll have a look into this but I can’t quite see how this is possible... The [worldgen json](https://github.com/Harleyoc1/DynamicTreesVampirism/blob/master/src/main/resources/assets/dynamictreesvampirism/worldgen/default.json) points specifically to `vampirism:vampireforest`.

**Comment by Harleyoc1** [comment]
Fixed in

**Comment by Harleyoc1** [comment]
Will upload the new file now.
