### ISSUE TITLE
DynamicTreesVampirism Failed to load 

### ISSUE THREAD

**Issue by IchigoGames** [Harleyoc1/DynamicTreesVampirism#2]
not sure why could be a Compatibly issue with newer forge im using but it will not load 

Minecraft 1.16.5
Forge 36.1.65
DynamicTrees-1.16.5-0.10.0-Beta18
DynamicTreesVampirism-1.16.5-1.1.2
Vampirism-1.16.5-1.8.0-beta.3

![image](https://user-images.githubusercontent.com/11888162/126530466-cd6c3236-941a-4804-85d4-32bdbf52c5bf.png)

log 
https://www.dropbox.com/s/j7z0kxzgi8z1n15/dynimic%20trees%20latest.log?dl=0

**Comment by supermassimo** [comment]
Dynamic Trees for Vampirism has yet to be updated to work with Dynamic Trees Beta 18

**Comment by IchigoGames** [comment]
oh ok i saw there was a update for it so i thought it was.

**Comment by VirtualGaming1** [comment]
im surprise that this mod have not been updated. the rest already have been updated. even the bigger Dynamic tree compact pack for BOP
